<?php
/**
 * Sofhere SofTicket Magento Component
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GNU (3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/gpl-3.0.html
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@sofhere.com so we can send you a copy immediately.
 * 
 * @category	design_default
 * @author 		sofhere.com
 * @package		Sofhere_SofTicket
 * @copyright  	Copyright (c) 2008-2009 Sofhere IT Solutions.(http://www.sofhere.com)
 * @version 		1.0
 * @license		http://opensource.org/licenses/gpl-3.0.html GNU GENERAL PUBLIC LICENSE (GNU 3.0) 
 */
?>
<?php


$customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
$orderCollection = Mage::getModel('sales/order')->getCollection()
    ->addFieldToFilter('customer_id', array('eq' => array($customer_id)));
$final_order = array();
$order_ids   = array();
array_push($final_order, "Select Order");
foreach($orderCollection AS $order_row){
		$order = $order_row->getData();
		$order_data = "Order # ".$order['increment_id']." - Placed on ".$order['created_at']." for $".$order['subtotal_incl_tax'];
		
		array_push($final_order, $order_data);
		array_push($order_ids, $order['entity_id']);
}
?>
<div class="padder">
<?php if($this->getTitle(null)): ?>

<div class="head-alt2">
     <h2 class="title"><?php echo $this->getTitle(null) ?></h2>
</div>
<div class="input-text">
     <h5 ><?php echo $this->__('Ticket Add Instruction') ?></h5>
</div>

<br>
        
<?php endif;?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl(0) ?>" method="post" id="form-validate">
    <fieldset class="group-select">
    	<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    	<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

        <ul>
            <li>
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Name') ?> <span class="required"></span></label><br />
                    <input type="text" name="name" value="<?php echo $this->getName() ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" id="name" />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="email"><?php echo Mage::helper('ticketsystem')->__('Email') ?> <span class="required"></span></label><br />
                    <input type="text" name="email" value="<?php echo $this->getEmail() ?>" title="<?php echo $this->__('Email') ?>" <?php if ($this->getEmail()<>'') { ?> readonly <?php } ?>class="required-entry input-text" id="email" />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="phone"><?php echo Mage::helper('ticketsystem')->__('Phone') ?> </label><br />
                    <input type="text" name="phone" value="" title="<?php echo $this->__('Phone') ?>" class="input-text" id="phone" />
                </div>
            </li>
 			<li>
            	<div class="box">
				    <label><?php echo Mage::helper('ticketsystem')->__('Select Department') ?></label><br/>
				        <select name="cat">
				        <?php foreach ($this->getDepartments() as $_code => $_name): ?>
				            <option value="<?php echo $_code ?>" >
				                <?php echo $_name->getName() ?> 
				            </option>
				        <?php endforeach; ?>
				        </select>
				</div>
            </li>
			<li>
                <div style="width:350px;">
                    <label for="ordername">Select Order</label><br />
                    <input type="hidden" id="orderid">
					<?php

$dropdown = '<select name="orders" onchange="document.getElementById(\'orderid\').value = this.value;">'."\n";

    $selected = "";
    /*** loop over the options ***/
    foreach( $final_order as $key=>$option )
    {
        /*** assign a selected value ***/
        $select = $selected==$key ? ' selected' : null;

        /*** add each option to the dropdown ***/
        $dropdown .= '<option value="'.$option.'"'.$select.'>'.$option.'</option>'."\n";
    }

    /*** close the select ***/
    $dropdown .= '</select>'."\n";

?> 
                    <?php echo $dropdown;?><br/>
                </div>
            </li>
            <li>
                <div style="width:350px;">
                    <label for="subject"><?php echo Mage::helper('ticketsystem')->__('Subject') ?> <span class="required"></span></label><br />
                    <input type="text" name="subject" value="" title="<?php echo Mage::helper('ticketsystem')->__('Subject') ?>" class="required-entry input-text" id="subject" />
                </div>
            </li>

            <li>
                <div class="input-box">
                    <label for="message"><?php echo Mage::helper('ticketsystem')->__('Message') ?> <span class="required"></span></label><br />
                    <textarea name="message" id="message" title="<?php echo $this->__('Message') ?>" class="required-entry" style="height:150px;width:525px;" cols="50" rows="5"></textarea>
                </div>
            </li>
            <li>
            	<div class="box">
				    <label><?php echo Mage::helper('ticketsystem')->__('Priority') ?><span class="required"></span></label><br/>
				        <select name="priority">
				        <?php foreach ($this->getPriorities() as $_code => $_name): ?>
				            <option value="<?php echo $_code ?>" >
				                <?php echo $_name ?> 
				            </option>
				        <?php endforeach; ?>
				        </select>
				</div>
            </li>
    	</ul>
    </fieldset>
   
    <div class="button-set">
        <p class="required"><?php echo Mage::helper('ticketsystem')->__('* Required Fields') ?></p>
        <a href="<?php echo $this->getBackUrl() ?>" class="f-left">&laquo; <?php echo $this->__('Back') ?></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button class="form-button" type="submit"><span><?php echo $this->__('Save Ticket') ?></span></button>
    </div>
</form>

<script type="text/javascript">
    var contactForm = new VarienForm('form-validate', true);
</script>  
</div>